/**
 * @phuetz/ai-providers — Shared LLM Provider Types
 *
 * Unified type definitions for multi-provider LLM communication.
 * Used by both Code Buddy (CLI agent) and Lisa (AI companion).
 */

// ============================================================================
// Provider Identity
// ============================================================================

/**
 * Supported AI provider identifiers.
 * Covers cloud providers (OpenAI, Anthropic, Google, xAI) and local runtimes.
 */
export type ProviderType =
  | 'openai'
  | 'anthropic'
  | 'gemini'
  | 'xai'
  | 'grok'
  | 'ollama'
  | 'lm-studio'
  | 'local'
  | 'mistral'
  | 'deepgram'
  | 'minimax'
  | 'moonshot'
  | 'venice'
  | 'z-ai';

/**
 * Capabilities that a provider may support.
 */
export type ProviderFeature =
  | 'streaming'
  | 'tools'
  | 'vision'
  | 'json_mode'
  | 'function_calling';

// ============================================================================
// Messages
// ============================================================================

/**
 * Standardized message format for LLM communication.
 * Compatible with OpenAI, Anthropic, Gemini, and xAI message formats.
 */
export interface LLMMessage {
  /** The role of the message sender. */
  role: 'system' | 'user' | 'assistant' | 'tool';
  /** The content of the message (text or null for tool-call-only messages). */
  content: string | null;
  /** Optional author name (used with tool role). */
  name?: string;
  /** Tool call ID this message responds to (required for role='tool'). */
  tool_call_id?: string;
  /** Tool calls generated by the model (present for role='assistant'). */
  tool_calls?: ToolCall[];
  /** Base64-encoded image or image URL (for vision-capable models). */
  image?: string;
}

// ============================================================================
// Tool Calling
// ============================================================================

/**
 * A tool call request from an LLM.
 * Uses OpenAI-compatible format (also used by xAI, LM Studio, Ollama).
 */
export interface ToolCall {
  /** Unique identifier for the tool call. */
  id: string;
  /** The type of tool call (currently only 'function'). */
  type: 'function';
  /** Function call details. */
  function: {
    /** The name of the function/tool to call. */
    name: string;
    /** JSON-encoded arguments string. */
    arguments: string;
  };
}

/**
 * Definition of a tool available to the LLM.
 * Uses OpenAI function-calling format.
 */
export interface ToolDefinition {
  /** The name of the tool. */
  name: string;
  /** A description of what the tool does. */
  description: string;
  /** JSON Schema defining the expected parameters. */
  parameters: JSONSchema;
}

/**
 * OpenAI-compatible tool wrapper (for API requests).
 */
export interface ToolWrapper {
  type: 'function';
  function: {
    name: string;
    description: string;
    parameters: JSONSchema;
  };
}

/**
 * Result of a tool execution, sent back to the LLM.
 */
export interface ToolResult {
  /** The tool_call_id this result responds to. */
  tool_call_id: string;
  /** The result content (typically JSON string). */
  content: string;
  /** Whether the tool execution failed. */
  error?: boolean;
}

/**
 * JSON Schema type for tool parameters.
 */
export interface JSONSchema {
  type: 'object' | 'string' | 'number' | 'boolean' | 'array' | 'integer' | 'null';
  description?: string;
  properties?: Record<string, JSONSchema>;
  required?: string[];
  items?: JSONSchema;
  enum?: (string | number | boolean)[];
  default?: unknown;
  additionalProperties?: boolean | JSONSchema;
}

// ============================================================================
// Responses
// ============================================================================

/**
 * Standardized response from an LLM provider.
 */
export interface LLMResponse {
  /** Unique response identifier. */
  id: string;
  /** The textual content (null if only tool calls). */
  content: string | null;
  /** Tool calls generated by the model. */
  toolCalls: ToolCall[];
  /** The reason generation stopped. */
  finishReason: FinishReason;
  /** Token usage statistics. */
  usage: TokenUsage;
  /** The specific model used. */
  model: string;
  /** The provider that generated the response. */
  provider: ProviderType;
}

export type FinishReason =
  | 'stop'
  | 'tool_calls'
  | 'length'
  | 'content_filter'
  | null;

export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

// ============================================================================
// Streaming
// ============================================================================

/**
 * A chunk of a streaming response.
 */
export interface StreamChunk {
  /** The type of data this chunk contains. */
  type: 'content' | 'tool_call' | 'done' | 'error';
  /** Text content delta (present if type='content'). */
  content?: string;
  /** Partial tool call data (present if type='tool_call'). */
  toolCall?: Partial<ToolCall>;
  /** Error message (present if type='error'). */
  error?: string;
  /** Whether this is the final chunk. */
  done?: boolean;
}

// ============================================================================
// Configuration
// ============================================================================

/**
 * Configuration for initializing a provider.
 */
export interface ProviderConfig {
  /** API key for authentication. */
  apiKey: string;
  /** Model identifier. */
  model?: string;
  /** Custom API base URL. */
  baseUrl?: string;
  /** Max tokens to generate. */
  maxTokens?: number;
  /** Sampling temperature (0-2). */
  temperature?: number;
  /** Request timeout in milliseconds. */
  timeout?: number;
  /** Max retry attempts. */
  maxRetries?: number;
}

/**
 * Options for a chat completion request.
 */
export interface CompletionOptions {
  /** The conversation history. */
  messages: LLMMessage[];
  /** Available tools. */
  tools?: ToolDefinition[];
  /** Sampling temperature override. */
  temperature?: number;
  /** Max tokens override. */
  maxTokens?: number;
  /** Whether to stream the response. */
  stream?: boolean;
  /** System prompt to prepend. */
  systemPrompt?: string;
  /** Force the model to use tools. */
  forceToolUse?: boolean;
  /** Current iteration in tool-calling loop. */
  toolCallIteration?: number;
}

// ============================================================================
// Model Capabilities
// ============================================================================

/**
 * Per-model capability configuration.
 * Uses glob pattern matching (e.g., 'gpt-4*', 'gemini-2.5*').
 */
export interface ModelCapabilities {
  /** Glob pattern for model name matching. */
  model: string;
  /** Context window size in tokens. */
  contextWindow?: number;
  /** Max output tokens. */
  maxOutputTokens?: number;
  /** Whether the model supports tool calling. */
  supportsToolCalls?: boolean;
  /** Whether the model supports vision/images. */
  supportsVision?: boolean;
  /** Whether the model supports structured reasoning. */
  supportsReasoning?: boolean;
  /** Enabled tool names (null = all). */
  enabledTools?: string[] | null;
  /** Disabled tool names. */
  disabledTools?: string[];
  /** Max tool call rounds per turn. */
  maxToolRounds?: number;
  /** Preferred patch format. */
  patchFormat?: 'unified' | 'search_replace' | 'full_file';
  /** System prompt template name. */
  systemPromptTemplate?: string;
}

// ============================================================================
// Provider Pricing
// ============================================================================

/**
 * Pricing per 1M tokens.
 */
export interface ProviderPricing {
  /** Cost per 1M input tokens (USD). */
  input: number;
  /** Cost per 1M output tokens (USD). */
  output: number;
}

// ============================================================================
// Error Types
// ============================================================================

/**
 * Categorized error types for retry/failover decisions.
 */
export type ErrorCategory =
  | 'transient'   // Retryable (rate limit, timeout, network)
  | 'auth'        // API key invalid
  | 'billing'     // Quota exceeded
  | 'permanent'   // Model not found, invalid request
  | 'network';    // Connection error

/**
 * Connection state for provider health tracking.
 */
export type ConnectionState =
  | 'connected'
  | 'connecting'
  | 'degraded'
  | 'disconnected'
  | 'cooldown';
